### ISSUE TITLE
Any plan for workspace support?

### ISSUE THREAD

**Issue by dehypnosis** [yhnavein/yarn-check#3]
Is this under maintaining?

**Comment by yhnavein** [comment]
Hi @dehypnosis 
I am no longer maintaining this :(

If you are looking for a similar tool that offers workspace support then I do recommend following command (built-in in yarn, so no need to install anything)
```
yarn upgrade-interactive --latest
```

**Comment by dehypnosis** [comment]
Yeah.. it was there! Thanks for information so much!
